<?php

namespace DoctrineProxies\__CG__\App\Models\Order\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Order extends \App\Models\Order\Entities\Order implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'order_number', 'order_date', 'status', 'billing_address_id', 'shipping_address_id', 'email', 'coupon_code', 'payment_method', 'shipping_amount', 'tax_amount', 'discount_amount', 'grand_total', 'shipping_method', 'volume', 'shipment', 'billing_address', 'shipping_address', 'order_items', '_em', 'hidden', 'createdAt', 'updatedAt'];
        }

        return ['__isInitialized__', 'id', 'order_number', 'order_date', 'status', 'billing_address_id', 'shipping_address_id', 'email', 'coupon_code', 'payment_method', 'shipping_amount', 'tax_amount', 'discount_amount', 'grand_total', 'shipping_method', 'volume', 'shipment', 'billing_address', 'shipping_address', 'order_items', '_em', 'hidden', 'createdAt', 'updatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Order $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getRepository()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepository', []);

        return parent::getRepository();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderNumber', []);

        return parent::getOrderNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderNumber($order_number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderNumber', [$order_number]);

        return parent::setOrderNumber($order_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderDate', []);

        return parent::getOrderDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderDate($order_date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderDate', [$order_date]);

        return parent::setOrderDate($order_date);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingAddressId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingAddressId', []);

        return parent::getBillingAddressId();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingAddressId($billing_address_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingAddressId', [$billing_address_id]);

        return parent::setBillingAddressId($billing_address_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingAddressId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingAddressId', []);

        return parent::getShippingAddressId();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingAddressId($shipping_address_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingAddressId', [$shipping_address_id]);

        return parent::setShippingAddressId($shipping_address_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getCouponCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCouponCode', []);

        return parent::getCouponCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCouponCode($coupon_code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCouponCode', [$coupon_code]);

        return parent::setCouponCode($coupon_code);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentMethod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentMethod', []);

        return parent::getPaymentMethod();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentMethod($payment_method)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentMethod', [$payment_method]);

        return parent::setPaymentMethod($payment_method);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingAmount', []);

        return parent::getShippingAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingAmount($shipping_amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingAmount', [$shipping_amount]);

        return parent::setShippingAmount($shipping_amount);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxAmount', []);

        return parent::getTaxAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxAmount($tax_amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxAmount', [$tax_amount]);

        return parent::setTaxAmount($tax_amount);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscountAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscountAmount', []);

        return parent::getDiscountAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscountAmount($discount_amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscountAmount', [$discount_amount]);

        return parent::setDiscountAmount($discount_amount);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrandTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrandTotal', []);

        return parent::getGrandTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrandTotal($grand_total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrandTotal', [$grand_total]);

        return parent::setGrandTotal($grand_total);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingMethod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingMethod', []);

        return parent::getShippingMethod();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingMethod($shipping_method)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingMethod', [$shipping_method]);

        return parent::setShippingMethod($shipping_method);
    }

    /**
     * {@inheritDoc}
     */
    public function getVolume()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVolume', []);

        return parent::getVolume();
    }

    /**
     * {@inheritDoc}
     */
    public function setVolume($volume)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVolume', [$volume]);

        return parent::setVolume($volume);
    }

    /**
     * {@inheritDoc}
     */
    public function getShipment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShipment', []);

        return parent::getShipment();
    }

    /**
     * {@inheritDoc}
     */
    public function setShipment(\App\Models\Shipment\Entities\Shipment $shipment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShipment', [$shipment]);

        return parent::setShipment($shipment);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingAddress', []);

        return parent::getBillingAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingAddress(\App\Models\Address\Entities\Address $billing_address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingAddress', [$billing_address]);

        return parent::setBillingAddress($billing_address);
    }

    /**
     * {@inheritDoc}
     */
    public function getShippingAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShippingAddress', []);

        return parent::getShippingAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setShippingAddress(\App\Models\Address\Entities\Address $shipping_address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShippingAddress', [$shipping_address]);

        return parent::setShippingAddress($shipping_address);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderItems()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderItems', []);

        return parent::getOrderItems();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderItems(array $order_items)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderItems', [$order_items]);

        return parent::setOrderItems($order_items);
    }

    /**
     * {@inheritDoc}
     */
    public function save()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'save', []);

        return parent::save();
    }

    /**
     * {@inheritDoc}
     */
    public function remove()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'remove', []);

        return parent::remove();
    }

    /**
     * {@inheritDoc}
     */
    public function fillFromArray(array $attributes = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fillFromArray', [$attributes]);

        return parent::fillFromArray($attributes);
    }

    /**
     * {@inheritDoc}
     */
    public function toJson($options = 0)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toJson', [$options]);

        return parent::toJson($options);
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function relationsToArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'relationsToArray', []);

        return parent::relationsToArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityManager()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityManager', []);

        return parent::getEntityManager();
    }

    /**
     * {@inheritDoc}
     */
    public function fill(array $attributes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fill', [$attributes]);

        return parent::fill($attributes);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTime $createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

}
